add EventList component
GunadarmaIO-Community/Frontend-Website-GunadarmaIO pull request #11
Opened 2022-03-17 08:05 UTC by falbas

2022-03-17 08:12 UTC, viantonugroho11 commented
![image](https://user-images.githubusercontent.com/74128119/158765332-326c625e-d42e-466b-8d5e-e1081eb81676.png)
lah ko begini

2022-03-17 08:14 UTC, viantonugroho11 requested changes

2022-03-17 08:14 UTC, viantonugroho11 commented on src/pages/index.tsx
> +import { Intro } from '@/modules/Intro/Intro'
![image](https://user-images.githubusercontent.com/74128119/158765608-02118aee-ae0d-4f04-8cd2-32eca6095e92.png)
Eror Disini

2022-03-17 08:26 UTC, falbas commented
@viantonugroho11 pull ulang
di gue aman soalnya

2022-03-17 08:27 UTC, falbas commented
![image](https://user-images.githubusercontent.com/77236568/158768338-084f32cc-7210-4623-9788-c89d77a2e21d.png)

2022-03-17 09:20 UTC, viantonugroho11 commented
Oke aman

2022-03-20 14:11 UTC, gregoriusjimmy commented on src/types/type.ts
> +export type EventListAPI = {
if this type represent one single event object, please rename it to `Event`

2022-03-20 14:11 UTC, gregoriusjimmy commented on src/components/modules/OurDivision/OurDivision.tsx
> +  // console.log(divisions)
remove this line

2022-03-20 14:11 UTC, gregoriusjimmy commented on src/components/modules/EventList/EventList.tsx
> +import { useState } from 'react'
remove unused import

2022-03-20 14:11 UTC, gregoriusjimmy commented on src/pages/index.tsx
> +  const getEventList = async (): Promise<EventListAPI[]> => {
rename this to `getEvents`

2022-03-20 14:11 UTC, gregoriusjimmy commented on src/pages/index.tsx
> +      const resEventList = await axios.get<GetEventListResponse>('event')
rename res or resEvents

2022-03-20 14:11 UTC, gregoriusjimmy commented on src/pages/index.tsx
> +  eventLists: EventListAPI[]
events

2022-03-20 14:11 UTC, gregoriusjimmy commented on src/components/modules/EventList/EventList.tsx
> +export const EventList = ({ eventLists }: Props) => {
so we will change this to ArticleSection

2022-03-20 14:11 UTC, gregoriusjimmy commented on src/components/modules/Event/Event.tsx
> +export const Event = () => {
rename this to EventSection to reduce confusion between the Event data

2022-03-25 02:49 UTC, falbas commented
![2022-03-25 09-40-58](https://user-images.githubusercontent.com/77236568/160044839-8a0d3c1a-186a-4472-9d19-d06610132b74.gif)

2022-03-25 03:08 UTC, falbas commented
![2022-03-25 10-06-29](https://user-images.githubusercontent.com/77236568/160046708-3c1fab65-ca79-466c-87a8-144a9775ce8f.gif)

2022-03-27 00:23 UTC, gregoriusjimmy approved these changes
CAKEPP MERGE!!

2022-03-27 02:32 UTC, viantonugroho11 commented
Mantap HAN

2022-03-27 08:42 UTC, merged