add event section
GunadarmaIO-Community/Frontend-Website-GunadarmaIO pull request #7
Opened 2022-03-10 03:05 UTC by falbas

2022-03-10 04:55 UTC, gregoriusjimmy approved these changes
Keren!
![image](https://user-images.githubusercontent.com/45916985/157592420-38ec2288-b98c-4824-9fbc-d9bafa1574a9.png)
![image](https://user-images.githubusercontent.com/45916985/157592460-5e4e2898-fe6a-4cab-9dce-5630f9908671.png)

2022-03-10 07:52 UTC, viantonugroho11 requested changes
Good Job han
tapi itu kan nanti carousell nah dia pindah cardnya apa isinya aja???

2022-03-10 12:00 UTC, Clayrisee commented
Untuk structured codenya udah rapih, maybe next stepnya bisa diprepare satu var untuk get api dan buat gambar dsbnya dynamic

2022-03-10 12:01 UTC, Clayrisee approved these changes

2022-03-11 06:06 UTC, gregoriusjimmy commented
> Good Job han tapi itu kan nanti carousell nah dia pindah cardnya apa isinya aja???

coba tanya anak design

2022-03-12 04:32 UTC, merged